### ISSUE TITLE
GroupIcons are all grey

### ISSUE THREAD

**Issue by 486** [awslabs/aws-icons-for-plantuml#15]
The [GroupIcons](https://github.com/awslabs/aws-icons-for-plantuml/tree/master/dist/GroupIcons) are all defined with grey color (`#232F3E`) although the list of [AWSSymbols](https://github.com/awslabs/aws-icons-for-plantuml/blob/master/AWSSymbols.md) shows them colored. I realized it when using `VPCSubnetPrivate` and `VPCSubnetPublic` which should be blue and green, respectively, like this:

```
!define VPCSubnetPrivate(e_alias, e_label, e_techn) AWSEntity(e_alias, e_label, e_techn, #147EBA, VPCSubnetPrivate, VPCSubnetPrivate)
!define VPCSubnetPrivate(e_alias, e_label, e_techn, e_descr) AWSEntity(e_alias, e_label, e_techn, e_descr, #147EBA, VPCSubnetPrivate, VPCSubnetPrivate)
!define VPCSubnetPublic(e_alias, e_label, e_techn) AWSEntity(e_alias, e_label, e_techn, #248814, VPCSubnetPublic, VPCSubnetPublic)
!define VPCSubnetPublic(e_alias, e_label, e_techn, e_descr) AWSEntity(e_alias, e_label, e_techn, e_descr, #248814, VPCSubnetPublic, VPCSubnetPublic)
```

Is this a bug or intentional?

**Comment by gadams999** [comment]
It was intentional on the initial release as everything _except_ the Group category was a single color. When back next week I’ll look at adding the ability to define colors on individual icons then create and generate a new set of icons.

These will live in the master branch for now but will them be picked up in the next quarterly release. 
 Thanks for bringing this up!

**Comment by gadams999** [comment]
Colors added to those that were not grey (SquidInk). Active in master branch, will be incorporated into the next icon release set.
