### ISSUE TITLE
SecurityGroup puml doesnot work

### ISSUE THREAD

**Issue by guneshsji** [awslabs/aws-icons-for-plantuml#51]
Its icon is also missing 
https://github.com/awslabs/aws-icons-for-plantuml/blob/c2a8677c8cf61464786ad6dc71a74616cf787f29/AWSSymbols.md

code i tried:
`!include AWSPuml/Groups/SecurityGroup.puml
SecurityGroup('SecurityGroup', 'Security Group', 'an optional tech label') {     note as note         the content of the group     end note }
`

**Comment by hakanson** [comment]
The Security Group is one of a few groups without an icon (also Generic Group and Availability Zone Group).

[Groups - all.puml](https://github.com/awslabs/aws-icons-for-plantuml/blob/main/examples/Groups%20-%20all.puml) has code examples using all the groups.  The macro is actually named `SecurityGroupGroup` since I appended `Group` to every group.

The code below is an update to what you tried

```
@startuml Issue 51

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/Groups/SecurityGroup.puml

SecurityGroupGroup(sg)  {
  note as note
    the content of the group
  end note
}

@enduml
```
